--liquibase formatted sql
--changeset lmat:V1-database-init.sql

CREATE TABLE CASH(
    ID BIGSERIAL PRIMARY KEY,
    IDENTIFIER VARCHAR NOT NULL,
    CUSTODIAN VARCHAR NOT NULL,
    OWNER VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    STATE VARCHAR NOT NULL,
    LATEST_UPDATE_TIMESTAMP BIGINT NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE CASH;

CREATE TABLE CASH_REQUESTS(
    ID BIGSERIAL PRIMARY KEY,
    CUSTODIAN VARCHAR NOT NULL,
    REQUESTER VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE CASH_REQUESTS;

CREATE TABLE SHARES(
    ID BIGSERIAL PRIMARY KEY,
    IDENTIFIER VARCHAR NOT NULL,
    CUSTODIAN VARCHAR NOT NULL,
    CORPORATION VARCHAR NOT NULL,
    OWNER VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    STATE VARCHAR NOT NULL,
    LATEST_UPDATE_TIMESTAMP BIGINT NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE SHARES;

CREATE TABLE SHARE_REQUESTS(
    ID BIGSERIAL PRIMARY KEY,
    CUSTODIAN VARCHAR NOT NULL,
    REQUESTER VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE SHARE_REQUESTS;

CREATE TABLE BUY_OFFERS(
    ID BIGSERIAL PRIMARY KEY,
    IDENTIFIER VARCHAR NOT NULL,
    CUSTODIAN VARCHAR NOT NULL,
    BUYER VARCHAR NOT NULL,
    CORPORATION VARCHAR NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURRENCY VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    LATEST_UPDATE_TIMESTAMP BIGINT NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE BUY_OFFERS;

CREATE TABLE SELL_OFFERS(
    ID BIGSERIAL PRIMARY KEY,
    IDENTIFIER VARCHAR NOT NULL,
    CUSTODIAN VARCHAR NOT NULL,
    SELLER VARCHAR NOT NULL,
    CORPORATION VARCHAR NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURRENCY VARCHAR NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    CONTRACT_ID VARCHAR NOT NULL,
    LATEST_UPDATE_TIMESTAMP BIGINT NOT NULL,
    ENTITY_VERSION BIGINT NOT NULL
);

--rollback DROP TABLE SELL_OFFERS;